# Generated by Django 3.1.5 on 2021-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image_upload',
            field=models.ImageField(default='defaultImg.png', upload_to='uploads/'),
        ),
    ]
