# Generated by Django 3.1.5 on 2021-02-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210227_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='glass_base',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
