# Generated by Django 3.1.5 on 2021-02-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210227_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='itemsOrdered',
            field=models.ManyToManyField(to='store.OrderItem'),
        ),
    ]
